### PR TITLE
Comment out the errors

### PR DESCRIPTION
**Pull request by expeon07**
Comment out the lines the give out errors. Not sure whether they are necessary.
// #define LOVE \n❤ 𝖀𝖓𝖈𝖔𝖓𝖉𝖎𝖙𝖎𝖔𝖓𝖆𝖑 𝕷𝖔𝖛𝖊 ❤
// #pragma message( STR(INFORMATION) )

### CODE REVIEW

**Comment by GiorgosXou** [comment]
They are **kind of** unnecessary *(they are mostly reminders\*)*, but it makes no sense why those two lines would produce any kind of errors *(maybe encoding ones?)*... could you please comment **where and how do you compile it? what version of gcc or g++ or Arduino do you use and what the error messages tell you?** 

\***those macros are mainly being used as reminds, to let users know whether or not they are able to use specific features of the library based on the user's `define`d function & property preferences**. Could you try just removing `LOVE` from `#define INFORMATION` and  let me know if it compiles, like so:

```c++
// #define LOVE \nheart 𝖀𝖓𝖈𝖔𝖓𝖉𝖎𝖙𝖎𝖔𝖓𝖆𝖑 𝕷𝖔𝖛𝖊 heart
...
#define INFORMATION MSG0 MSG1 MSG2 ... \\ <--- LOVE IS REMOVED
#pragma message( STR(INFORMATION) )
```

**Comment by expeon07** [comment]
Hi, I'm using the Arduino IDE to upload the code on an Arduino Uno. 
image
I get this error after following your suggestion

**Comment by GiorgosXou** [comment]
This doesn't look as an error, what you are looking at  is an indication\reminder that the macro `#prgma message( STR(INFORMATION) )` was executed and the output of it was `[ƒx] |‣ Sigmoid |‣ Tanh |⌥|` which means that you used\`defined` Sigmoid & Tanh functions inside your sketch

**Comment by GiorgosXou** [comment]
could you please copy & paste the whole console output?

**Comment by expeon07** [comment]
Hi, here is the whole output 

```
In file included from Arduino/libraries/NeuralNetwork/examples/Any_Activation_Function_Per_Layer/Any_Activation_Function_Per_Layer.ino:8:0:
Arduino/libraries/NeuralNetwork/src/NeuralNetwork.h:304:35: note: #pragma message: 
[ƒx] |‣ Sigmoid |‣ Tanh |⌥|
 #pragma message( STR(INFORMATION) )
                                   ^
Sketch uses 8484 bytes (26%) of program storage space. Maximum is 32256 bytes.
Global variables use 398 bytes (19%) of dynamic memory, leaving 1650 bytes for local variables. Maximum is 2048 bytes.
```

**Comment by GiorgosXou** [comment]
**This is not an error**, this is a **`note`**\message\reminder that your sketch\code uses Sigmoid and Tanh, it literally says `/NeuralNetwork.h:304:35: note: #pragma message`  

**And It compiles Successfully:**
```terminal
Sketch uses 8484 bytes (26%) of program storage space. Maximum is 32256 bytes.
Global variables use 398 bytes (19%) of dynamic memory, leaving 1650 bytes for local variables. Maximum is 2048 bytes.
```

**Pull request closed without merging**
