### PR TITLE
Fixes some issues with running on the Teensy

### PR DESCRIPTION
**Pull request by chriskiefer**
Name space clashes with Teensy when using audio
File open/close when using Teensy SD card library

### CODE REVIEW

**Comment by GiorgosXou** [comment]
**Did you see this [comment](
https://github.com/MusicallyEmbodiedML/NeuralNetworks/commit/5b48c8a8106a7452a03ad04c3e308669ccb09a4c#r148011013).** If you are experiencing any undefined behavior or crush due to [this](https://github.com/GiorgosXou/NeuralNetworks/commit/875e3d6e6a279f8b6f705bf6f141b4297ca874a5), it's definetely not an issue of the library **but** an issue with the way you implemented and used the NN under `REDUCE_RAM_DELETE_OUTPUTS`-optimization in your sketch.

**Comment by chriskiefer** [comment]
Hi, strange, i'm not sure how the REDUCE_RAM_DELETE_OUTPUTS regression happened, please ignore that part of this pull request. Sorry perhaps it would be helpful if i had explained a bit more about this PR - i'm running a workshop this week and we're using this library - it's working really well, and we haven't experienced undefined behaviours.  We're running the workshop using Teensy 4.1 boards, and I'm sharing a few adjustments that I made to get the library to work on these boards - renaming A1-A3 because there's a clash, and some small changes to the way files are opened in load/save because teensy has a slightly different API for its own SD card library.  The adjustments should be backwards compatible i hope.

**Comment by GiorgosXou** [comment]
> *Hi, strange, i'm not sure how the REDUCE_RAM_DELETE_OUTPUTS regression happened, please ignore that part of this pull request*

**No wories**, I think it has to do with the fact that this specific improvement wasn't included to the latest version.

> *i'm running a workshop this week and we're using this library - it's working really well, and we haven't experienced undefined behaviours.*

**Sounds pretty interesting!** I'd like to know more about it - niceee. I've seen you entered our discord server, if you had any issue with the verification let me know and I will manually verify you once I see you again.

> *I'm sharing a few adjustments that I made to get the library to work on these boards*

**I was able to merge** [this](https://github.com/GiorgosXou/NeuralNetworks/commit/3d9246c9f6d4e0a02243cda7c7c192c0d1e285f9) change **but** unfortunately I had to refactor&drop [this](https://github.com/GiorgosXou/NeuralNetworks/pull/41/commits/5b48c8a8106a7452a03ad04c3e308669ccb09a4c) one before merging.

> *The adjustments should be backwards compatible i hope.*

**Thanks for your interest and contribution, now everythings should be fine**. I'll push the new version in a few minutes and it should be available in arduino's library manager **in a few hours** *(or the next day)*.

**Comment by GiorgosXou** [comment]
image

**Comment by GiorgosXou** [comment]
**Done,** Should be available in arduino's library manager in a few hours *(or the next day)*:
https://github.com/GiorgosXou/NeuralNetworks/releases

**Comment by GiorgosXou** [comment]
@chriskiefer check [this warning](https://github.com/GiorgosXou/NeuralNetworks/releases/tag/v3.0.0-beta)

**Pull request closed without merging**
